### ISSUE TITLE
Использование без домена

### ISSUE THREAD

**Issue by KyuremBoG** [CLLlAgOB/free2fa#1]
День добрый, возможно ли как то использовать ваше решение без домена?

**Comment by CLLlAgOB** [comment]
Конкретно в этом виде нет. Но можно переписать.
А где у вас хранятся пользователи?

Вт, 4.06.2024 в 11:54, KyuremBoG ***@***.***>:

**Comment by KyuremBoG** [comment]
Извиняюсь за долгий ответ. Локально, на машине.

**Comment by CLLlAgOB** [comment]
Нет, данная сборка не предназначена для использования локальных
пользователей. Только Active Directory, однако ее можно адаптировать, при
желании и знаниях вы можете это сделать.

Вс, 9.06.2024 в 10:01, KyuremBoG ***@***.***>:
