### ISSUE TITLE
realm: Not authorized to perform this action Error: Failed to join the domain

### ISSUE THREAD

**Issue by anonimousnouser** [CLLlAgOB/free2fa#2]
При установке, после ввода домена, dc и мени доменного пользователя возникает следующая ошибка:
**_realm: Not authorized to perform this action
Error: Failed to join the domain_**
Доступ к KDC есть, могу получить TGS через kinit.

**Comment by CLLlAgOB** [comment]
Проверьте конфиг кербероса и и realm. Если вы
Указывали несколько серверов домена важно соблюдать формат. Или возможно у
пользователя под которым вы пытаетесь добавить сервер в домен нет на это
прав.

Ср, 5.06.2024 в 11:05, anonimousnouser ***@***.***>:

**Comment by anonimousnouser** [comment]
Спасибо, помогло - нужно было исправить конфиг realm.
Но появилась новая проблема). Так как репозитории docker.io недоступны без VPN, а возможности использовать VPN нет (ограничения стенда), то появляется connection timeout. Пытался указывать прокси в разделе environment файла docker-compose.yml, но не срабатывает, та же ошибка соединения - connection timeout.
Если есть вариант решения, то пожалуйста подскажите))

**Comment by CLLlAgOB** [comment]
Вы можете скачать исходники и скомпилировать их на месте.
Они доступны на гитлабе папка docker
Туда надо положить ваш .evn файл и docker-compose .yml только в последнем
надо поменять источник вместо image: clllagob…… везде заменить на build: и
путь к папкам приложения.
Например build: ./free2fa_setup
Потом проверить фалы Dockerfile и если там указаны конкретные версии
компонентов просто удалить номер версии что бы скачалось последняя версия
так как старые могут быть уже не доступны.
После чего в папке где лежит docker-compose.yml набрать docker-compose
build
И дождаться пока соберется контейнер потом просто запустить его командой
docker-compose up -d ну и посмотреть логи командой docker-compose logs -f

Ср, 5.06.2024 в 16:29, anonimousnouser ***@***.***>:

**Comment by CLLlAgOB** [comment]
Либо вариант проще
https://habr.com/ru/articles/818527/


Ср, 5.06.2024 в 16:44, Alexander Voloskov ***@***.***>:

**Comment by anonimousnouser** [comment]
Помогло указание прокси в файле /etc/systemd/system/docker.service.d/http-proxy.conf
[Service]
Environment="HTTP_PROXY=http://proxy.example.com:3128"
Environment="HTTPS_PROXY=https://proxy.example.com:3129"
Теперь другая проблема)
Контейнеры скачиваются, но после этого процесс, установки зависает.
Опытным путем определили (systemctl status free2fa), что проблема связана с сертификатами:
start_service.sh[784]: Waiting for /var/lib/docker/volumes/2fa_free2fa_ca_certs/_data/ca.crt certificate to be created..
Дальше пока ступор...

**Comment by CLLlAgOB** [comment]
Удали все волюмы контейнера. И запусти заново. Если не поможет удали все и
сделай с нуля. А ты случайно не переименовывал контейнера? Что то менял в
файле docker-compose.yml?

Ср, 5.06.2024 в 19:08, anonimousnouser ***@***.***>:

**Comment by anonimousnouser** [comment]
Все снес под ноль, установил заново - заработало. 
Добавил пользователей, телеграмм id.
Хочу использовать Ваше решение как второй фактор в SoftEtherVPN.
Подскажите пожалуйста, дальнейшая настройка заключается в настройке конфига freeradius и softether, верно?

**Comment by CLLlAgOB** [comment]
Фрирадиус уже настроен из коробки. Вам надо только настроить со стороны
SoftEther VPN.


чт, 6 июн. 2024 г. в 09:42, anonimousnouser ***@***.***>:

**Comment by anonimousnouser** [comment]
Настроил SoftEther c Radius-аутентификацией (дополнительно правили файл /etc/freeradius/3.0/clients.conf, добавив ipaddr и secret параметры шлюза), но к серверу VPN не подключается.
Не могли бы подсказать, где я могу посмотреть логи free2fa, может они дадут ответ на вопрос?

**Comment by CLLlAgOB** [comment]
Чтобы просмотреть журналы Docker, следующие в каталог установки, выполните
команду:
docker-compose logs -f

Чтобы получить доступ к журналам FreeRADIUS, выполните следующую команду:
cat /var/log/freeradius/radius.log

или вы можете просмотреть все журналы в одном окне с помощью команды:
tail -f /var/log/freeradius/radius.log & docker-compose logs -f

 В файле конфигурации /etc/freeradius/3.0/clients.conf задается от кого
фрирадиус будет принимать запросы и секрет. Обратите внимание если у вас
сервер за натом то надо указать ип ната.
Вам надо скорее всего посмотреть что происходит сначала в freeradius по
этому сначала остановите его.
И запустите его уже в дебаг режиме:

Чтобы запустить FreeRADIUS в режиме отладки, сначала остановите службу
FreeRADIUS, выполнив команду:
service freeradius stop
Затем, чтобы запустить FreeRADIUS в режиме отладки, введите:
freeradius -Xx

Но если вы хотите использовать один сервер 2fa для например впн и для
скажем вифи доступа рекомендую использовать этот скрипт он добавит/удалит
правильно конфиги.

https://github.com/CLLlAgOB/free2fa/blob/main/control.sh



Чт, 6.06.2024 в 16:49, anonimousnouser ***@***.***>:
